title: "Francisco Lopes"
description: "Computer Engineering Student | AI & DevOps"
baseurl: ""
url: "https://francisc0lopes.github.io"

# TEMA SIMPLES - REMOVE remote_theme que causa erro
theme: jekyll-theme-cayman

# Informações básicas
author:
  name: "Francisco Lopes"
  email: "franciscolopes1132003@gmail.com"

# SEM plugins complexos, SEM remote_theme, SEM defaults
