title: "Francisco Lopes"
description: "Computer Engineering Student | AI & DevOps"
baseurl: ""
url: "https://francisc0lopes.github.io"

# Tema que suporta a estrutura que queres
remote_theme: mmistakes/minimal-mistakes

# Plugins essenciais apenas
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Informações básicas
author:
  name: "Francisco Lopes"
  email: "franciscolopes1132003@gmail.com"

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"